### ISSUE TITLE
Echec du téléchargement du fichier sécurisé

### ISSUE THREAD

**Issue by emmanuelsantune** [ansforge/psc-admin-portal#73]
Lorsque l'on télécharge un fichier sécurisé en cliquant sur "Télécharger l'extraction" ou "Télécharger l'extraction de test", on obtient un message d'erreur
![2024-09-11 19_00_45-Window](https://github.com/user-attachments/assets/64caa3d4-ce69-4645-aec3-06d45dc90288)

**Comment by edegenetais-nx** [comment]
Hello @emmanuelsantune ! Je pense qu'il y a ici deux problèmes séparés :

1. Téléchargement de l'extraction
1. Téléchargement de l'extraction de test

- Concernant l'extraction, je vais regarder de quoi il retourne.
- Pour l'extraction de test, j'ai une question : comme ce fichier est un fichier mis en place et mis à jour manuellement, il est possible qu'il n'y en ait pas en dev (pour ma part, je n'ai pas uploadé de fichier de test). As-tu essayé d'uploader un fichier de test ? J'en attache un s'il t'en faut un exemple.
[test-extraction-example.zip](https://github.com/user-attachments/files/17077425/test-extraction-example.zip)

**Comment by emmanuelsantune** [comment]
Bonjour!

En fait , pour le téléchargement de l'extraction de test, je vais dans "Gestion des processus" puis "Téléchargement du fichier sécurisé" et je clique sur "télécharger l''extraction de test" et j'ai un message d'erreur "Echec du téléchargement de l'extrait".

**Comment by edegenetais-nx** [comment]
> Bonjour!
> 
> En fait , pour le téléchargement de l'extraction de test, je vais dans "Gestion des processus" puis "Téléchargement du fichier sécurisé" et je clique sur "télécharger l''extraction de test" et j'ai un message d'erreur "Echec du téléchargement de l'extrait".

OK. Ma question est la suivante : est-ce qu'il ne t'a pas manqué une info sur la fonctionnalité qui a mené à cette erreur : le téléchargement du fichier de test ne peut marcher que si le fichier de test a été d'abord uploadé par quelqu'un. Je pense que personne n'a jamais uploadé de fichier, sauf si toi tu l'as fait. Or si on ne t'a pas informé que c'est un pré-requis, tu ne pouvais pas le savoir.

**Comment by edegenetais-nx** [comment]
Concernant le problème de téléchargement de l'extrait, il s'agit probablement d'une conséquence de l'anomalie #78 . Je propose de mettre ce ticket en attente jusqu'à ce que l'anomalie #78 soit résolue.

**Comment by emmanuelsantune** [comment]
Suite au déploiement de la version 1.0.0.r6 le fichier sécurisé a pu être téléchargé

**Comment by edegenetais-nx** [comment]
@emmanuelsantune : donc tu fermes l'issue ?
