### ISSUE TITLE
Redirection liens

### ISSUE THREAD

**Issue by emmanuelsantune** [ansforge/psc-admin-portal#75]
Lorsque l'utilisateur clique sur les liens donnés en PJ, ll est redirigé vers la page d'accueil
![2024-09-19 18_57_11-Window](https://github.com/user-attachments/assets/248ec812-0a84-4fee-9fc4-153ec8bb807e)

ainsi que sur le symbole suivant
![2024-09-19 18_58_46-Window](https://github.com/user-attachments/assets/3035ed7a-5c1e-4e76-8e16-f1ae57f63f8d)

**Comment by edegenetais-nx** [comment]
@emmanuelsantune : oui, il s'agit d'un problème dans le template fourni par le projet DesignSystem pour le pied de page.

@laura-murat : est-ce que tu peux regarder, s'il te plaît ? (of course en fonction aussi du planning ROC)

**Comment by edegenetais-nx** [comment]
@emmanuelsantune : peux tu regarder si ma livraison 1.0.0.rc4 du 24/09/2024 au soir résoud ce problème ?

**Comment by emmanuelsantune** [comment]
Bonjour eric. C'est à la même url ? Je viens de me déconnecter et me reconnecter mais le problème persiste. Cependant, je ne peux plus me connecter à l'appli à présent

**Comment by edegenetais-nx** [comment]
bonjour,
je vais regarder et je reviens vers toi.

**Comment by edegenetais-nx** [comment]
> Bonjour eric. C'est à la même url ? 
Oui, même URL.
> Je viens de me déconnecter et me reconnecter mais le problème persiste (les liens redirigent vers la page d'accueil). 
Je ne peux pas diagnostiquer les pages internes (problème ProSanteConnect BAS, donc connexion impossible) mais au niveau dela page d'accueil je confirme.
> Cependant, l'état des composants est instable (j'ai plusieurs KO)
Je pense que sur ce point c'est dû aux problèmes PSC

**Comment by emmanuelsantune** [comment]
Après redéploiement 1.0.0.rc6, les liens redirigent bien vers les pages correspondantes

**Comment by edegenetais-nx** [comment]
OK, Issue définitivement fermée.
