### ISSUE TITLE
Arrêt du processus de chargement du RASS

### ISSUE THREAD

**Issue by emmanuelsantune** [ansforge/psc-admin-portal#78]
Lors du lancement du processus de chargement du RASS, ce dernier s'arrête à la levée des alertes : 

![image](https://github.com/user-attachments/assets/0cfac334-8b9f-4cd2-9bbb-f775b52d0ca4)

Cependant, aucune alerte n'est relevée dans le diff de la section "Gestion des alertes"

![image](https://github.com/user-attachments/assets/2464953b-9d78-4237-8890-aaf8c8f7bc5d)

**Comment by edegenetais-nx** [comment]
Après inspection de l'état de l'instance de test :
1. le blocage est dû au déclenchement des alertes. Le problème est le suivant : une ou plusieurs alertes se déclenchent quand le nombre de PS mis à jour ou supprimé dépasse 5% du nombre total de PS. Or comme la base de données est vide, la formule fait une division par zéro qui déclenche l'alerte. C'est un cas à la marge, qui devrait être traité en demandant de continuer malgré l'alerte, mais ce n'est pas possible du fait que les alertes ne sont pas détectées dans le portail.
1. la non-détection des alertes semble lié  un problème de différence de configuration du composant alertmanager entre le poste de développement et l'instance de recette. Ce problème serait identique en cas de déploiement en préproduction ou production.

Je vais reproduire le problème en développement (en corrigeant la configuration appliquée sur le poste de développement) et corriger le problème de détection des alertes.

**Comment by edegenetais-nx** [comment]
@emmanuelsantune : quand la version psc-admin-portal 1.0.0.rc4 sera livrée, vois si les alertes apparaissent, et si ça permet de débloquer le processus avec le bouton force-continue (qui doit apparaître quand les alertes sont détectées)

**Comment by emmanuelsantune** [comment]
Bonjour.

Après livraison de la version 1.0.0.rc6, la levée des alertes est fonctionnelle et le diff est téléchargeable et consultable.

![image](https://github.com/user-attachments/assets/e7674db4-dd96-4bc2-948c-a179856081d8)
![image](https://github.com/user-attachments/assets/642c532a-90c1-4c00-8e01-8704c8699cb2)
