### ISSUE TITLE
Les files d'attentes rabbitMQ ne sont pas trouvées

### ISSUE THREAD

**Issue by emmanuelsantune** [ansforge/psc-admin-portal#90]
Lorsqu'on se connecte à RabbitMQ et que l'on clique sur une file d'attente, une page "Not Found" apparait

![image](https://github.com/user-attachments/assets/874964eb-6350-4d4a-8cca-93705d07e65c)
![image](https://github.com/user-attachments/assets/0dd22144-8ec9-495d-b156-6ccd33a7bf82)

Cordialement

**Comment by edegenetais-nx** [comment]
Le bug a été confirmé en comparant le fonctionnement de l'instance rabbitMQ de recette à travers le portail admin (le défaut apparaît) et en direct (en ouvrant un tunnel SSL pour ouvrir directement rabbitMQ dans le navigateur). Reste comprendre ce qui fait échouer le proxy sur cette URL en particulier.

**Comment by emmanuelsantune** [comment]
Testé OK
